name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: ricardochaves/python-lint@v1.2.0
      with:
        use-pylint: false
        use-mypy: false
